Opencontrail support on stable/queens
Changes to add opencontrail support to contrail/queens branch
1. init containers for nova and neutron
2. do not use 'pip install docker'. Use 'pip install docker-py' as is done in
ocata. the docker 3.3.0 from the pip repository has issues that cause the
ansible docker_container module to throw errors like below:
TypeError: load_config() got an unexpected keyword argument \\'config_dict\\

Change-Id: I82c7624866f2ae7c4b35ee95e64033f88c1c0040